@extends('layouts.admin')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4">
    <div><h3 class="fw-bold mb-1">Salary Structures</h3><p class="text-muted mb-0">Manage effective salary packages for Junoxen employees.</p></div>
    <a href="{{ route('admin.salary-structures.create') }}" class="btn btn-primary"><i class="bi bi-plus-lg me-1"></i> New Salary Structure</a>
</div>
<div class="card mb-4"><div class="card-body"><form class="row g-2" method="GET"><div class="col-md-5"><select name="employee_id" class="form-select"><option value="">All employees</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected(request('employee_id')==$employee->id)>{{ $employee->employee_id }} - {{ $employee->full_name }}</option>@endforeach</select></div><div class="col-md-3"><select name="status" class="form-select"><option value="">All statuses</option><option @selected(request('status')==='Active')>Active</option><option @selected(request('status')==='Inactive')>Inactive</option></select></div><div class="col-md-4 d-flex gap-2"><button class="btn btn-primary">Filter</button><a class="btn btn-outline-secondary" href="{{ route('admin.salary-structures.index') }}">Reset</a></div></form></div></div>
<div class="card"><div class="card-body p-0"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Employee</th><th>Basic</th><th>Allowances</th><th>Deductions</th><th>Effective</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>
@forelse($structures as $s)
<tr><td><strong>{{ $s->employee->full_name }}</strong><div class="small text-muted">{{ $s->employee->employee_id }} · {{ $s->employee->department?->name }}</div></td><td>₹{{ number_format((float)$s->basic_salary,2) }}</td><td>₹{{ number_format((float)$s->hra+(float)$s->conveyance_allowance+(float)$s->medical_allowance+(float)$s->special_allowance+(float)$s->other_allowance,2) }}</td><td>₹{{ number_format((float)$s->pf_deduction+(float)$s->esi_deduction+(float)$s->professional_tax+(float)$s->tds+(float)$s->loan_deduction+(float)$s->other_deduction,2) }}</td><td>{{ $s->effective_from->format('d M Y') }}<div class="small text-muted">to {{ $s->effective_to?->format('d M Y') ?? 'Open-ended' }}</div></td><td><span class="badge {{ $s->status==='Active'?'bg-success':'bg-secondary' }}">{{ $s->status }}</span></td><td class="text-end"><a href="{{ route('admin.salary-structures.edit',$s) }}" class="btn btn-sm btn-outline-primary">Edit</a><form method="POST" action="{{ route('admin.salary-structures.destroy',$s) }}" class="d-inline" onsubmit="return confirm('Delete this salary structure?');">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Delete</button></form></td></tr>
@empty<tr><td colspan="7" class="text-center text-muted py-5">No salary structures found.</td></tr>@endforelse
</tbody></table></div></div></div><div class="mt-3">{{ $structures->links() }}</div>
@endsection
